#!/bin/sh

set -e



action="$1"
oldversion="$2"

update-alternatives \
    --install /usr/bin/x-terminal-emulator \
      x-terminal-emulator /usr/bin/stterm 15 \
    --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
      x-terminal-emulator.1.gz \
      /usr/share/man/man1/stterm.1.gz

# End of file


